### ISSUE TITLE
Getting the project started!

### ISSUE THREAD

**Issue by karx** [Sscorp9412/Interns-edvanta#1]
> Hi @Sscorp9412 , here is a template that you can use for the Readme, I have tried to define your project in my words, feel free to reach out if I am needed for further.

## Introduction
Hi, this is a 5-day project made by `` during Internship '21 at Edvanta Technologies

##  Project Overview
To Create a webpage, that tests and reports Browser API status in the current session.
List of available APIs:
* https://developer.mozilla.org/en-US/docs/Web/API

## Technologies Used
* Web Browser APIs
* Glitch
* React

## References 
* https://developer.mozilla.org/en-US/docs/Web/API

## FAQs

**Comment by Sscorp9412** [comment]
![Screenshot from 2021-11-10 12-22-41](https://user-images.githubusercontent.com/59340190/141064331-74f5f718-ec2b-4596-a3d9-ef283df3ef9a.png)
<h1><b>Completed</b></h1>
